a Shell script that runs a Python script.

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,6 @@
 #!/bin/bash
-python3 $PYFILE
+if [ -z "$PYFILE" ]; then
+	echo "Error: Environment variable \$PYFILE is not set."
+	exit 1
+fi
+python3 "$PYFILE"
